language: python
python: 3.7

env:
  global:
    # Doctr deploy key for pcdshub/M2K2
    - secure: "Fzhu9pit/q4Hei6oaEQDLDNp/3tiqviQAOBaphWCEtYexxD71z3slAmacwUB8zwTkTFdbtL3/ZI0BJ1rKIFr2ZZqjIrz+kXxq1n6j0/MI4j16ljrZPrVy4oyjaRGXWQJ3l5RYv9GZyVuyy7HH83lp6tK42NPjaLvD2GXrGmBzEttlZoFIzqjsXt1w5nz4MMITAy5UcK/VYkezsAmgFxLwN0j17DfhDZZ5Gl2YDyYp2uqU2EcV1w54iCgyw2zYl9QoaYBTmZi0EVQBVHnhYD2e5bwkphsrq+pe4zmo5a+vKtPiGu/iMQIOFs195Ue3li9oPE+blxHDkROEbk84JY1s8WWXAPE5B9C+mR2nB5oRRjvqUqqSikBROkBQaIhPoFzDsSbfsCGtwstWz69zxbZ6F0gXKe0vwtgCuYLfm6CZP1u4X919KF34YVstrbX+l0Sk+TiaNaOdeOyv01IsdCV+dZ4I3KXB80gERUEvVT4yRRF5TAu0Zz5bhdWf4xnHV/6+jAGTDmUC18CQZFCFn+5bEn6E8KXwgH6LBGF85/jxpgEuS3gxUO+e+46MepQLnB1vPlMUGVIKGLx2baYhg9+LuQ5EPjndTxXzxL15APekl5DiSkCoft8uwVLviJjIXXtYSf8xmhG0pG8HrRlRISIEFxmpOxWo6u6Ydra/+X26Y0="
    - TWINCAT_STYLE_EXCLUDE=
    # If using a custom version of the CI helpers, change the following in
    # addition to the `import` block elow:
    # - CI_HELPER_URL=https://github.com/klauer/pcds-ci-helpers
    # - CI_HELPER_BRANCH=twincat_shared_configs

# Uncomment this block if you would like to make a test an allowed failure
#jobs:
#  allow_failures:
#    - name: "Style Check"
#    - name: "Pre-commit Checks"

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/standard.yml

# If not using the standard-python-conda above please uncomment the required
# (language, os, dist and stages) and optional (import statements) entries from
# the blocks below.
#
#language: python
#os: linux
#dist: xenial
#
#stages:
#  - build
#  - test
#  - name: deploy
#    if: (branch = master OR tag IS present) AND type != pull_request
#
#import:
#  # Build stage
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/setup.yml
#  # Test stage
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/docs-build.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/pragmalint.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/pre-commit.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/style.yml
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/summary.yml
#  # Deploy stage
#  - pcdshub/pcds-ci-helpers:travis/shared_configs/twincat/doctr-upload.yml
